var stuDb = {
    "zhangela301@hotmail.com": {
        "FirstName": "Hans",
        "LastName": "Li",
        "GradeLevel": "9",
        "Email": "zhangela301@hotmail.com",
        "School": "Damien high school",
        "Title": "Minecraft Parkour",
        "Video": "https://www.youtube.com/watch?v=hUh2Uv5_QHA&list=PLSO4tiuu6d-GeiD4ZL1uItJEkep9mhi6l&index=147",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 84,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "I didn't know you could use python to interact with Minecraft! Really good job with the block generation code"
    },
    "ljx20090108@gmail.com": {
        "FirstName": "Barry",
        "LastName": "Li",
        "GradeLevel": "9",
        "Email": "ljx20090108@gmail.com",
        "School": "Northwood High School",
        "Title": "Coin Pickup",
        "Video": "https://www.loom.com/share/7775b773d8234ac5ac420f55f2de6e25",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 83,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "Really good job with the overall game. Lots of potential for additional features."
    },
    "ttywl8888@gmail.com": {
        "FirstName": "Yirina",
        "LastName": "Wang",
        "GradeLevel": "9",
        "Email": "ttywl8888@gmail.com",
        "School": "Santa Margarita Catholic High School",
        "Title": "Hangman",
        "Video": "https://drive.google.com/file/d/1MOKkNBYYYhrUbVLbyxtzvaL-wPKTkKaH/view?usp=sharing",
        "Attendence": "N",
        "Division": "Division G9-12",
        "Score": 76,
        "Rank": "Top 42%",
        "Award": "Finalist",
        "Comment": "No show"
    },
    "ericquexinrui0606@gmail.com": {
        "FirstName": "Xinrui",
        "LastName": "Que",
        "GradeLevel": "10",
        "Email": "ericquexinrui0606@gmail.com",
        "School": "Crean Lutheran High School",
        "Title": "Sentiment score by AI",
        "Video": "https://youtu.be/QC0E3oz3PhA",
        "Attendence": "N",
        "Division": "Division G9-12",
        "Score": 75,
        "Rank": "Top 42%",
        "Award": "Finalist",
        "Comment": "No show"
    },
    "sandrapoly@yahoo.com": {
        "FirstName": "Andrew",
        "LastName": "Zhou",
        "GradeLevel": "9",
        "Email": "sandrapoly@yahoo.com",
        "School": "Northwood High school",
        "Title": "Connect 4",
        "Video": "https://www.youtube.com/watch?v=CtkD43kkjyU",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 90,
        "Rank": "Top 19%",
        "Award": "Second Place Prize",
        "Comment": "Really great job in identifying that you could use a function to reduce the amount of redundant code!"
    },
    "963192951@qq.com": {
        "FirstName": "Jiuyu",
        "LastName": "Zhang",
        "GradeLevel": "9",
        "Email": "963192951@qq.com",
        "School": "La Jolla Country Day School",
        "Title": "Aero Air Flight Simulator",
        "Video": "https://www.youtube.com/watch?v=8N1Lo_ULQlQ",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 90,
        "Rank": "Top 19%",
        "Award": "Second Place Prize",
        "Comment": "Super in-depth project. Having a presentation helps a lot but I recommend keeping a better track of time"
    },
    "angelinazhao217@gmail.com": {
        "FirstName": "Angelina",
        "LastName": "Zhao",
        "GradeLevel": "9",
        "Email": "angelinazhao217@gmail.com",
        "School": "Santa Margarita Catholic High School",
        "Title": "Atari Breakout",
        "Video": "https://www.youtube.com/watch?v=-CT_hXsdoyY&list=PLSO4tiuu6d-GeiD4ZL1uItJEkep9mhi6l&index=229&ab_channel=CodingMinds",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 93,
        "Rank": "Top 8%",
        "Award": "First Place Prize",
        "Comment": "Very Impressive Project! Really good job in identifying bugs and future improvements. Lots of potential"
    },
    "yqhiee@gmail.com": {
        "FirstName": "Xuanwei",
        "LastName": "Ding",
        "GradeLevel": "9",
        "Email": "yqhiee@gmail.com",
        "School": "Northwood high school",
        "Title": "The Haunted House RPG Game",
        "Video": "https://youtu.be/zePIp6QA58k",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 85,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "Really like the idea of using a dictionary to store the objects and descritions"
    },
    "vivianhyteng@gmail.com": {
        "FirstName": "Kevin",
        "LastName": "Hu",
        "GradeLevel": "9",
        "Email": "vivianhyteng@gmail.com",
        "School": "Sage Hill School",
        "Title": "Cyberops",
        "Video": "https://youtu.be/sp9wUWzg7RI",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 88,
        "Rank": "Top 19%",
        "Award": "Second Place Prize",
        "Comment": "Nice job getting together a clone of Cyberpunk so quickly. Well Done!"
    },
    "judith.jing@gmail.com": {
        "FirstName": "Zachary",
        "LastName": "liang",
        "GradeLevel": "9",
        "Email": "judith.jing@gmail.com",
        "School": "Saint Margaret's Escopical School",
        "Title": "Water World RPG",
        "Video": "https://youtu.be/IsOV4rxuDuU",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 94,
        "Rank": "Top 8%",
        "Award": "First Place Prize",
        "Comment": "Very impressive project. A lot of work when in this. (Look into exploring databases) Keep it up!"
    },
    "cindyzhenhua@gmail.com": {
        "FirstName": "Jason",
        "LastName": "Xiao",
        "GradeLevel": "9",
        "Email": "cindyzhenhua@gmail.com",
        "School": "Portola High School",
        "Title": "platformer",
        "Video": "https://youtu.be/F44wOi-e694",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 84,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "Awesome detailed explanation of the project. Add more assets and a win state!"
    },
    "kevinxu0628@gmail.com": {
        "FirstName": "Haowei",
        "LastName": "Xu",
        "GradeLevel": "9",
        "Email": "kevinxu0628@gmail.com",
        "School": "Northwood high school",
        "Title": "test review",
        "Video": "https://www.youtube.com/watch?v=5YBgNqZ_K4Y&list=PLSO4tiuu6d-GeiD4ZL1uItJEkep9mhi6l&index=17",
        "Attendence": "N",
        "Division": "Division G9-12",
        "Score": 76,
        "Rank": "Top 42%",
        "Award": "Finalist",
        "Comment": "No show"
    },
    "shihporsche@gmail.com": {
        "FirstName": "Nicky",
        "LastName": "Shih",
        "GradeLevel": "9",
        "Email": "shihporsche@gmail.com",
        "School": "Pacific Academy",
        "Title": "Alternative Reality",
        "Video": "https://m.youtube.com/watch?v=0nGabqgQ3WA&list=PLSO4tiuu6d-GeiD4ZL1uItJEkep9mhi6l&index=199",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 85,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "Appreciate your willingness to use such an intimidating technology"
    },
    "kevinying0712@hotmail.com": {
        "FirstName": "Kevin",
        "LastName": "Ying",
        "GradeLevel": "9",
        "Email": "kevinying0712@hotmail.com",
        "School": "Portola High",
        "Title": "Fooled!",
        "Video": "https://www.youtube.com/watch?v=JvJ55uUHg9s",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 89,
        "Rank": "Top 19%",
        "Award": "Second Place Prize",
        "Comment": "Appreciate your willingness to use such an intimidating technology"
    },
    "zhangxiaoling@gmail.com": {
        "FirstName": "Nicole",
        "LastName": "Ma",
        "GradeLevel": "9",
        "Email": "zhangxiaoling@gmail.com",
        "School": "Sage Hill School",
        "Title": "88 Magic Ball",
        "Video": "https://youtu.be/798HcBUFsqc",
        "Attendence": "Y ",
        "Division": "Division G9-12",
        "Score": 95,
        "Rank": "Top 8%",
        "Award": "First Place Prize",
        "Comment": "\"Very out of the box thinking, these types of programs are what the world relies on.\""
    },
    "joeycrj@gmail.com": {
        "FirstName": "Hanwen",
        "LastName": "Mai",
        "GradeLevel": "9",
        "Email": "joeycrj@gmail.com",
        "School": "Orange Lutheran High School",
        "Title": "Third Person Ball Maze",
        "Video": "https://youtu.be/LK7cTLYJdVA",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 88,
        "Rank": "Top 19%",
        "Award": "Second Place Prize",
        "Comment": "I'm impressed at the 3D work instead of simply doing a 2D game."
    },
    "srhzhg@gmail.com": {
        "FirstName": "Joshua",
        "LastName": "Tian",
        "GradeLevel": "9",
        "Email": "srhzhg@gmail.com",
        "School": "Beckman High School",
        "Title": "Eat mor Chickin",
        "Video": "https://youtu.be/Nhl676zQR34",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 88,
        "Rank": "Top 19%",
        "Award": "Second Place Prize",
        "Comment": "\"Using AI and Neural learning is the future, using this and applying to music was very impressive. \""
    },
    "tinayao0716@gmail.com": {
        "FirstName": "Charles",
        "LastName": "Tian",
        "GradeLevel": "9",
        "Email": "tinayao0716@gmail.com",
        "School": "University High School",
        "Title": "Obstacle Course with Turtle",
        "Video": "https://www.youtube.com/watch?v=KEu2DrSa_zA",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 85,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "Great concept and the game is absolutly playable."
    },
    "amanda_1109@msn.com": {
        "FirstName": "Colin Chen",
        "LastName": "Wang",
        "GradeLevel": "9",
        "Email": "amanda_1109@msn.com",
        "School": "Ningbo Haishu No.2 Foreign Language School",
        "Title": "A useful type system in Minecraft",
        "Video": "https://www.youtube.com/watch?v=hmMag6k0C0I&list=PLSO4tiuu6d-GeiD4ZL1uItJEkep9mhi6l&index=236",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 84,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "\"Excellent program that is useful, to be able to command other applications to perform tasks are very important\""
    },
    "carolgeng1226@gmail.com": {
        "FirstName": "Jiayu",
        "LastName": "Zhang",
        "GradeLevel": "10",
        "Email": "carolgeng1226@gmail.com",
        "School": "Northwood High School",
        "Title": "Car Racer",
        "Video": "https://youtu.be/Pbt3G8SHiQ4",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 83,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "This looks like a good start for a racing game -- level design is a very critical part for a lot of games and is a good skill to practice.  I liked the symmetry in your level"
    },
    "qianjing0822@outlook.com": {
        "FirstName": "Carson",
        "LastName": "Wu",
        "GradeLevel": "9",
        "Email": "qianjing0822@outlook.com",
        "School": "Troy High School",
        "Title": "Parkour",
        "Video": "https://youtu.be/aN4h2pMGO9k",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 89,
        "Rank": "Top 19%",
        "Award": "Second Place Prize",
        "Comment": "Great understanding of the development. Interesting game concept."
    },
    "peteryang022106@gmail.com": {
        "FirstName": "Peter",
        "LastName": "Yang",
        "GradeLevel": "9",
        "Email": "peteryang022106@gmail.com",
        "School": "Troy Highschool",
        "Title": "\"\"\"Breakout\"\"\"",
        "Video": "https://www.youtube.com/watch?v=4hElv0yWNXk",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 87,
        "Rank": "Top 19%",
        "Award": "Second Place Prize",
        "Comment": "Liked the candy concept of the game. Great understanding of code portion."
    },
    "wenwen8210@gmail.com": {
        "FirstName": "Kevin",
        "LastName": "Yang",
        "GradeLevel": "9",
        "Email": "wenwen8210@gmail.com",
        "School": "Orange County School of the Arts",
        "Title": "Rpg Survival Simulator",
        "Video": "https://www.youtube.com/watch?v=XsXudRb-us0&list=PLSO4tiuu6d-GeiD4ZL1uItJEkep9mhi6l&index=2",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 81,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "Very intriguing game paths with different choices. Liked the different end result based on player choice."
    },
    "lucasjosh33514@gmail.com": {
        "FirstName": "Charles",
        "LastName": "Yin",
        "GradeLevel": "9",
        "Email": "lucasjosh33514@gmail.com",
        "School": "La Salle College Preparatory",
        "Title": "Cartoonifier",
        "Video": "https://www.youtube.com/watch?v=fQMZeNf15hs",
        "Attendence": "N",
        "Division": "Division G9-12",
        "Score": 76,
        "Rank": "Top 42%",
        "Award": "Finalist",
        "Comment": "No show"
    },
    "7bascom@gmail.com": {
        "FirstName": "Sunny",
        "LastName": "Zhao",
        "GradeLevel": "9",
        "Email": "7bascom@gmail.com",
        "School": "University High School",
        "Title": "<<Turtle in goal>>",
        "Video": "https://www.youtube.com/watch?v=BnuMMr7wKos&list=PLSO4tiuu6d-GeiD4ZL1uItJEkep9mhi6l&index=240",
        "Attendence": "N",
        "Division": "Division G9-12",
        "Score": 75,
        "Rank": "Top 42%",
        "Award": "Finalist",
        "Comment": "No show"
    },
    "rachelw791220@gmail.com": {
        "FirstName": "Nathan",
        "LastName": "Lee",
        "GradeLevel": "9",
        "Email": "rachelw791220@gmail.com",
        "School": "Northwood Highschool",
        "Title": "Terravania",
        "Video": "https://www.youtube.com/watch?v=Knrjbv7wxbw",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 97,
        "Rank": "Top 8%",
        "Award": "First Place Prize",
        "Comment": "Great combination of mixing two games. Expansive character ability and understanding of code."
    },
    "mindy1969@126.com": {
        "FirstName": "Jinhui(Peter)",
        "LastName": "Chen",
        "GradeLevel": "10",
        "Email": "mindy1969@126.com",
        "School": "Corona Del Mar high school",
        "Title": "Skateboarding physics unity game",
        "Video": "https://www.youtube.com/watch?v=uQJY14jwDS0",
        "Attendence": "N",
        "Division": "Division G9-12",
        "Score": 75,
        "Rank": "Top 42%",
        "Award": "Finalist",
        "Comment": "No show"
    },
    "qaqaqaaa111@gmail.com": {
        "FirstName": "John",
        "LastName": "Song",
        "GradeLevel": "10",
        "Email": "qaqaqaaa111@gmail.com",
        "School": "Woodbridge High School",
        "Title": "Forrealm",
        "Video": "https://youtu.be/F4GxnsTUPX4",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 94,
        "Rank": "Top 8%",
        "Award": "First Place Prize",
        "Comment": "\"Excellent work integrating advanced technoligies like WebGL, WebSockets, and NodeJS to produce a polished and working game, with lots of though given to engineering design!\""
    },
    "jing102508@gmail.com": {
        "FirstName": "Justin",
        "LastName": "Li",
        "GradeLevel": "10",
        "Email": "jing102508@gmail.com",
        "School": "Troy High School",
        "Title": "Math Bot RPG",
        "Video": "https://www.youtube.com/watch?v=xWWVDT_N73Y",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 90,
        "Rank": "Top 19%",
        "Award": "Second Place Prize",
        "Comment": "\"Excellent work integrating with the Discord API, and focusing on modularity for future expansion!\""
    },
    "hongyandu@gmail.com": {
        "FirstName": "David",
        "LastName": "Tang",
        "GradeLevel": "10",
        "Email": "hongyandu@gmail.com",
        "School": "Irvine High School",
        "Title": "A Short Game Starring A VRoid",
        "Video": "https://www.youtube.com/watch?v=Fu-eylvyuAY&list=PLSO4tiuu6d-GeiD4ZL1uItJEkep9mhi6l&index=23",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 84,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "\"Great work integrating an open source plugin, it is always a challege to read documentation and learn how to use something that someone else built.\""
    },
    "catherineyx227@gmail.com": {
        "FirstName": "Sirui",
        "LastName": "Liu",
        "GradeLevel": "10",
        "Email": "catherineyx227@gmail.com",
        "School": "Orange Lutheran High School",
        "Title": "Secret XII Plan ",
        "Video": "https://youtu.be/JimYItDg96Y",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 82,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "Great work getting out of your comfort zone and learning a new technology!"
    },
    "ellyzhang3@126.com": {
        "FirstName": "Yunxiang",
        "LastName": "Zhang",
        "GradeLevel": "10",
        "Email": "ellyzhang3@126.com",
        "School": "Beijing Academy",
        "Title": "Architecture Pictionary Game",
        "Video": "https://youtu.be/01vlmIY83Ws",
        "Attendence": "N",
        "Division": "Division G9-12",
        "Score": 75,
        "Rank": "Top 42%",
        "Award": "Finalist",
        "Comment": "No show"
    },
    "maryqin12@gmail.com": {
        "FirstName": "Charles",
        "LastName": "Huang",
        "GradeLevel": "10",
        "Email": "maryqin12@gmail.com",
        "School": "Richmond Christian Secondary School",
        "Title": "Run Away",
        "Video": "https://youtube.com/watch?v=LfdPAErgdNE&feature=share",
        "Attendence": "N",
        "Division": "Division G9-12",
        "Score": 75,
        "Rank": "Top 42%",
        "Award": "Finalist",
        "Comment": "No show"
    },
    "lawrenceee0126@gmail.com": {
        "FirstName": "Tianyu (Lawrence)",
        "LastName": "Li",
        "GradeLevel": "10",
        "Email": "lawrenceee0126@gmail.com",
        "School": "St. George's School",
        "Title": "Players' Next Word Predictor",
        "Video": "https://youtu.be/osfcZTVqBF8",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 87,
        "Rank": "Top 19%",
        "Award": "Second Place Prize",
        "Comment": "A nicely made Markov Chain based Next Word Prediction -- the ideas of future works were good"
    },
    "lingw3307@gmail.com": {
        "FirstName": "Daniel",
        "LastName": "Wang",
        "GradeLevel": "10",
        "Email": "lingw3307@gmail.com",
        "School": "Troy High School",
        "Title": "Simple Battle Simulator",
        "Video": "https://youtu.be/bh9qzWYABgU",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 86,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "\"A good core for a turn based RPG -- I think that you should spend some time balancing and adding some element of randomness, because as is, there is no drama (no good luck or bad luck, you always know what you are getting)\""
    },
    "jchang9912@yahoo.com": {
        "FirstName": "Brian",
        "LastName": "Chang",
        "GradeLevel": "9",
        "Email": "jchang9912@yahoo.com",
        "School": "Beckman High School",
        "Title": "Unbeatable TicTacToe AI",
        "Video": "https://youtu.be/6l4YvRsMjT0",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 89,
        "Rank": "Top 19%",
        "Award": "Second Place Prize",
        "Comment": "A well made minimax algorithm for Tic-Tac-Toe -- I think it would be interesting to try it out in other games and see how it does"
    },
    "shichunjing1234@163.com": {
        "FirstName": "Congyu",
        "LastName": "Zhao",
        "GradeLevel": "9",
        "Email": "shichunjing1234@163.com",
        "School": "Northwood high school",
        "Title": "csgo in unity",
        "Video": "https://www.youtube.com/watch?v=uwtWCWYgoWs",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 95,
        "Rank": "Top 8%",
        "Award": "First Place Prize",
        "Comment": "You seem to have done a good job reimplementing Dust2 and in creating new assets for an FPS"
    },
    "apexwing2013@gmail.com": {
        "FirstName": "Ivy",
        "LastName": "Chen",
        "GradeLevel": "10",
        "Email": "apexwing2013@gmail.com",
        "School": "Troy High School",
        "Title": "Connect Four Plus",
        "Video": "https://youtu.be/ce3pgt0Ua-U",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 91,
        "Rank": "Top 19%",
        "Award": "Second Place Prize",
        "Comment": "Nice implementation.For Futher development of the game try to create a mobile app using flutter"
    },
    "piao1936@163.com": {
        "FirstName": "James",
        "LastName": "Jin",
        "GradeLevel": "10",
        "Email": "piao1936@163.com",
        "School": "Crean Lutheran High School",
        "Title": "SafeLink",
        "Video": "https://youtu.be/iy2ctEab5qY",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 81,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "Good implementation try using different page ranking and web crawling techniques to fix the ranking problem"
    },
    "jinge111505@gmail.com": {
        "FirstName": "Jinge",
        "LastName": "Liu",
        "GradeLevel": "10",
        "Email": "jinge111505@gmail.com",
        "School": "Portola High School",
        "Title": "Digital Text Recognition",
        "Video": "https://youtu.be/RQuGRh5mpJ4",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 96,
        "Rank": "Top 8%",
        "Award": "First Place Prize",
        "Comment": "really impressed with implementation.for further development try to convert into a app for mobile devices."
    },
    "janez93@hotmail.com": {
        "FirstName": "Daniel",
        "LastName": "Yu",
        "GradeLevel": "10",
        "Email": "janez93@hotmail.com",
        "School": "Irvine High",
        "Title": "21 java card game.",
        "Video": "https://youtu.be/fq44dSp-kHg",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 81,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "\"nice try.also try to add the symbols like the ace,queen etc into the game and try to make the game graphical.\""
    },
    "jordanchen2005@gmail.com": {
        "FirstName": "Huaiyue",
        "LastName": "Chen",
        "GradeLevel": "10",
        "Email": "jordanchen2005@gmail.com",
        "School": "Northwood High School",
        "Title": "Painting Tool",
        "Video": "https://www.youtube.com/watch?v=Q4WGnjyb0II&feature=emb_title&ab_channel=CodingMinds",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 82,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "\"Good implementation.couple of suggestions add a reset button to get a blank screen and also try to add more styulus like pen, pencil ,brush etc.\""
    },
    "jackgao05@gmail.com": {
        "FirstName": "Jack",
        "LastName": "Gao",
        "GradeLevel": "11",
        "Email": "jackgao05@gmail.com",
        "School": "Sagehill School",
        "Title": "\"SafetyLifeTime: An Interactive and Intuitive Game-based Disaster Training System. \"",
        "Video": "https://youtu.be/xmCz6RghJFc",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 92,
        "Rank": "Top 19%",
        "Award": "Second Place Prize",
        "Comment": "\"This is a great format for teaching disaster safety in different situations. I thought the progression of the game was really spot on for learning. One small thing, the object prompts should probably take up less space in the UI. \""
    },
    "a13910302819@gmail.com": {
        "FirstName": "Lirui",
        "LastName": "Huang",
        "GradeLevel": "11",
        "Email": "a13910302819@gmail.com",
        "School": "University High School",
        "Title": "The Real Shopping Ranks",
        "Video": "https://www.youtube.com/watch?v=rsxkSf6BM1w",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 86,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "\"Super cool idea to incorporate comment sentiment analysis in the score along with the actual product rating. Nice clean UI for dispalying the products. It would be interesting to figure out how to get the loading times down, maybe there could be some caching? \""
    },
    "john.xiao@outlook.com": {
        "FirstName": "Thomas",
        "LastName": "Xiao",
        "GradeLevel": "11",
        "Email": "john.xiao@outlook.com",
        "School": "Yorba Linda High School",
        "Title": "Sleepy Eyes-Sleepiness Detection",
        "Video": "https://youtu.be/HAdt7FdZZXA",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 87,
        "Rank": "Top 19%",
        "Award": "Second Place Prize",
        "Comment": "\"Great work producing a polished and super useful end-to-end app. As you're moving to eh app store, definitely fine-tuning the how fast the bar increases and decreases is really important. Make sure to collect some data in real life situations of people who are gaming and sleepy. \""
    },
    "ljin89@gmail.com": {
        "FirstName": "Charles",
        "LastName": "Yang",
        "GradeLevel": "11",
        "Email": "ljin89@gmail.com",
        "School": "Northwood High",
        "Title": "Safe Drive",
        "Video": "https://youtu.be/H9e9Ez9rUUk",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 97,
        "Rank": "Top 8%",
        "Award": "First Place Prize",
        "Comment": "\"Nicely polished, and detail oriented driving tutorial with an impressive use of events to simulate real driving. \""
    },
    "czhou948@gmail.com": {
        "FirstName": "Chenxi",
        "LastName": "Zhou",
        "GradeLevel": "11",
        "Email": "czhou948@gmail.com",
        "School": "Portola High School",
        "Title": "Blackjacks Card game",
        "Video": "https://www.youtube.com/watch?v=z2WnCyhR8S4&list=PLSO4tiuu6d-GeiD4ZL1uItJEkep9mhi6l&index=153",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 85,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "\"Great start to a fun blackjack game. A few things to take it to the next level: Make the card draw probabailites equal to a 52 card deck; As you said in your next steps, allow for multiple sessions so players can experience their winnings going up and down across bets. \""
    },
    "sha_zhang@yahoo.com": {
        "FirstName": "Amanda",
        "LastName": "Zhu",
        "GradeLevel": "11",
        "Email": "sha_zhang@yahoo.com",
        "School": "Portola High School",
        "Title": "Procrash: A Solution to Procrastination by Limiting Online Game Distractions Using Optical Character Recognition",
        "Video": "https://youtu.be/j9mlgdKjnIQ",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 96,
        "Rank": "Top 8%",
        "Award": "First Place Prize",
        "Comment": "\"This was a really cool project, I loved how you integrated so many third party tools and libraries into your project. Also I really liked how much thought went into the user experience especially when you were determining how to exit the distracting task. I loved the data and competitor analysis in your video. \""
    },
    "wuguoqing@toptexltd.com": {
        "FirstName": "Yucheng",
        "LastName": "Wu",
        "GradeLevel": "10",
        "Email": "wuguoqing@toptexltd.com",
        "School": "Crean Lutheran High School",
        "Title": "Python Gamegala Project",
        "Video": "https://youtu.be/KWl6VDhfqMc",
        "Attendence": "N",
        "Division": "Division G9-12",
        "Score": 76,
        "Rank": "Top 42%",
        "Award": "Finalist",
        "Comment": "No show"
    },
    "alicesces@gmail.com": {
        "FirstName": "Aaron",
        "LastName": "Tse",
        "GradeLevel": "10",
        "Email": "alicesces@gmail.com",
        "School": "Arcadia High School",
        "Title": "Space Invaders Math",
        "Video": "https://www.youtube.com/watch?v=qn4FkE_tzVo",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 93,
        "Rank": "Top 8%",
        "Award": "First Place Prize",
        "Comment": "Good code structure using multiple classes to split up the logic really helps!"
    },
    "li3223526426@gmail.com": {
        "FirstName": "Sherlock",
        "LastName": "Li",
        "GradeLevel": "10",
        "Email": "li3223526426@gmail.com",
        "School": "WCHS",
        "Title": "Snake game",
        "Video": "https://youtu.be/-ocza4AvUbM",
        "Attendence": "N",
        "Division": "Division G9-12",
        "Score": 75,
        "Rank": "Top 42%",
        "Award": "Finalist",
        "Comment": "No show"
    },
    "xiaoying39369@gmail.com": {
        "FirstName": "Richard",
        "LastName": "Yu",
        "GradeLevel": "10",
        "Email": "xiaoying39369@gmail.com",
        "School": "Santa Margarita Catholic High School",
        "Title": "Pure RNG",
        "Video": "https://youtu.be/SMqWp5uf5FU",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 88,
        "Rank": "Top 19%",
        "Award": "Second Place Prize",
        "Comment": "Great creativity with items and good use of java.util.Random"
    },
    "joeyzhuo678@yahoo.com": {
        "FirstName": "Qiongxia",
        "LastName": "Zhuo",
        "GradeLevel": "10",
        "Email": "joeyzhuo678@yahoo.com",
        "School": "Arcadia high school",
        "Title": "Unity UI game",
        "Video": "https://www.youtube.com/watch?v=YRbvzRNVQI8&feature=youtu.be",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 82,
        "Rank": "Top 28%",
        "Award": "Third Place Prize",
        "Comment": "This was a really cool idea with tons of potential"
    },
    "dingruoxi0921@gmail.com": {
        "FirstName": "Ruoxi(Alivia)",
        "LastName": "Ding",
        "GradeLevel": "10",
        "Email": "dingruoxi0921@gmail.com",
        "School": "Woodbridge High School",
        "Title": "Amazon Sentiment Analysis Project",
        "Video": "https://www.youtube.com/watch?v=SiuANEvldDM&feature=youtu.be",
        "Attendence": "Y",
        "Division": "Division G9-12",
        "Score": 91,
        "Rank": "Top 19%",
        "Award": "Second Place Prize",
        "Comment": "\"This was a great use of external libraries and a very useful project idea, give me this in a Chrome extension and I'm sold!\""
    },
    "pingpendroy@cox.net": {
        "FirstName": "Ethan",
        "LastName": "Pendroy",
        "GradeLevel": "10",
        "Email": "pingpendroy@cox.net",
        "School": "San Clemente",
        "Title": "Project Water Polo",
        "Video": "https://youtu.be/EzVAQ5BGXYg",
        "Attendence": "N",
        "Division": "Division G9-12",
        "Score": 75,
        "Rank": "Top 42%",
        "Award": "Finalist",
        "Comment": "No show"
    }
}